name: CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Generate dist files
        run: |
          npm install
          npm run build
      
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.2.0
        with:
          # Create incremental commit instead of doing push force
          keep_history: true
          # Build directory to deploy
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
